version: "3.5"

services:
  verif-front:
    build: .
    image: registry.reo.ru/rt/verif-front
    container_name: verif-front
    ports:
      - "8091:80"
    environment:
      VUE_APP_API_URL: ${VUE_APP_API_URL}
      VUE_APP_PPK_API_URL: ${VUE_APP_PPK_API_URL}
      VUE_APP_YANDEX_API_KEY: ${VUE_APP_YANDEX_API_KEY}
    restart: always
    networks:
      - verif-front_net 
networks:
  verif-front_net: 
